---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure ZooKeeper is running
      ansible.builtin.service:
        name: zookeeper
        state: started
      register: result
      check_mode: true
      failed_when: result is changed

    - name: Ensure a cluster leader has been elected
      ansible.builtin.uri:
        url: http://localhost:8080/commands/leader
        return_content: true
      register: result
      changed_when: false
      failed_when: >-
        result.status != 200 or
        result.json is not defined or
        result.json.error is not defined or
        result.json.error

    - name: Log ZooKeeper leader command output
      ansible.builtin.debug:
        var: result.json

- name: Verify instance3
  hosts: instance3
  gather_facts: false
  tasks:
    - name: Ensure Prometheus metrics provider is enabled
      ansible.builtin.uri:
        url: http://localhost:7000/metrics
        return_content: true
      register: result
      changed_when: false
      failed_when: result.status != 200
