zookeeper_version: 3.9.3
zookeeper_download_url: >-
  https://dlcdn.apache.org/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz
zookeeper_download_checksum: >-
  sha512:d44d870c1691662efbf1a8baf1859c901b820dc5ff163b36e81beb27b6fbf3cd31b5f1f075697edaaf6d3e7a4cb0cc92f924dcff64b294ef13d535589bdaf143

zookeeper_server_inventory_hosts: "{{ groups['zookeeper_servers'] }}"

# for caching of zookeeper archives
zookeeper_local_download_directory: ~/.cache/ansible/zookeeper
